BEGIN;
DO
$$
BEGIN
    BEGIN
        ALTER TABLE IF EXISTS event ADD COLUMN IF NOT EXISTS archive_link TEXT;
        ALTER TABLE IF EXISTS event ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT true;
    EXCEPTION
        WHEN duplicate_column THEN NULL;
    END;
END;
$$;
COMMIT;
