version: '2.2'
services:
  eventsdb:
    image: postgres:latest
    container_name: eventsdb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  vh-srv-events:
    container_name: vh-srv-events
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: "${DB_HOST}"
      PGPORT: ${DB_PORT}
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: ${DB_DATABASE}
      DB_APPNAME: "bbdev"
      APP_PORT: "${APP_PORT}"
      APP_MODE: "${APP_MODE}"
    image: vh-srv-events
    env_file:
      - .env
    depends_on:
      - eventsdb
    restart: always
    # cpus: '0.5'
    mem_limit: 250M
    ports:
      - 8080:8080
# networks:
#     default:
#         external:
#             name: vh
