BEGIN;

DROP TABLE IF EXISTS participation_status CASCADE;
DROP TABLE IF EXISTS event_participation_option CASCADE;
DROP TABLE IF EXISTS event_item CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS item_broadcast_url CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS broadcast_url CASCADE;
DROP TABLE IF EXISTS participant CASCADE;
DROP TABLE IF EXISTS audience CASCADE;
DROP TABLE IF EXISTS platform CASCADE;
DROP TABLE IF EXISTS participation_option CASCADE;
DROP TABLE IF EXISTS country_list CASCADE;
DROP TABLE IF EXISTS language_list CASCADE;

COMMIT;
